version: '2.1'
networks: {}
services:
  balena-factoryreset-example:
    build:
      context: .
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.update.strategy: kill-then-download